### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by wildanm** [QbDVision-Inc/mySQL-slow-log-analyzer#1]
```
# node slowLogAnalyzer.js /var/log/mysql/mariadb-slow.log
Reading /var/log/mysql/mariadb-slow.log...
/home/testlbifib/tuning/MySQLSlowLogAnalyzer/slowLogAnalyzer.js:71
      currentTiming.connectionId = parseInt(match[1]);
                                                 ^

TypeError: Cannot read property '1' of null
    at Interface.readInterface.on.line (/home/testlbifib/tuning/MySQLSlowLogAnalyzer/slowLogAnalyzer.js:71:50)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:451:12)
    at ReadStream.ondata (readline.js:165:10)
    at ReadStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
```
    
    

# node --version
v10.19.0

**Comment by wildanm** [comment]
I can fix it by changing : 

const match = line.match(/# User@Host: .* Id: *([0-9]+)/); 

to : 

const match = line.match(/# Thread_id: *([0-9]+)/);

**Comment by rsshilli** [comment]
Hello @wildanm,

Can you give me a sample of what your MariaDB file looks like? That would help me.

Ryan

**Comment by Berdir** [comment]
Seeing this too, the line that it is complaining about looks like this:

```
# User@Host: USER[USER] @  [IP]
```
I added a if (match) around it to just ignore that.

**Comment by rsshilli** [comment]
@Berdir I'd love a patch or a PR.

**Comment by rsshilli** [comment]
Closing this issue since there isn't enough information and no response.
