### ISSUE TITLE
Getting TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by bsmolyanov** [QbDVision-Inc/mySQL-slow-log-analyzer#5]
I am getting this error, when trying to read a MariaDB slow queries log.

`Reading mariadb-slow.log...
/tmp/MySQLSlowLogAnalyzer/slowLogAnalyzer.js:86
      currentTiming.connectionId = parseInt(match[1]);
                                                 ^

TypeError: Cannot read property '1' of null
    at LineByLineReader.<anonymous> (/tmp/MySQLSlowLogAnalyzer/slowLogAnalyzer.js:86:50)
    at LineByLineReader.emit (events.js:314:20)
    at LineByLineReader._nextLine (/tmp/MySQLSlowLogAnalyzer/node_modules/line-by-line/line-by-line.js:129:8)
    at Immediate.<anonymous> (/tmp/MySQLSlowLogAnalyzer/node_modules/line-by-line/line-by-line.js:134:9)
    at processImmediate (internal/timers.js:461:21)`

**Comment by rsshilli** [comment]
I can't reproduce this error, but it looks like some people on MariaDB have found the fix submitted by @zaober in #2 useful. Closing this a duplicate.
